import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import type { Company } from '../types';

// ─── CSV Export ───
export function exportToCSV(filename: string, headers: string[], rows: (string | number)[][]) {
    const escape = (v: string | number) => {
        const s = String(v);
        return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s;
    };
    const csvContent = [headers.map(escape).join(','), ...rows.map(row => row.map(escape).join(','))].join('\n');
    const BOM = '\uFEFF';
    const blob = new Blob([BOM + csvContent], { type: 'text/csv;charset=utf-8;' });
    downloadBlob(blob, `${filename}.csv`);
}

// ─── PDF Export ───
export function exportToPDF(
    reportTitle: string,
    company: Company | null,
    headers: string[],
    rows: (string | number)[][],
    dateRange?: { from: string; to: string }
) {
    const doc = new jsPDF({ orientation: headers.length > 6 ? 'landscape' : 'portrait' });
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 15;

    // Company header
    if (company) {
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(company.name || 'Company', pageWidth / 2, y, { align: 'center' });
        y += 6;
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        if (company.address) {
            doc.text(`${company.address}, ${company.city || ''} - ${company.pincode || ''}`, pageWidth / 2, y, { align: 'center' });
            y += 4;
        }
        if (company.gstin) {
            doc.text(`GSTIN: ${company.gstin}`, pageWidth / 2, y, { align: 'center' });
            y += 4;
        }
    }

    // Report title + date range
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    y += 3;
    doc.text(reportTitle, pageWidth / 2, y, { align: 'center' });
    y += 5;
    if (dateRange) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text(`Period: ${dateRange.from} to ${dateRange.to}`, pageWidth / 2, y, { align: 'center' });
        y += 6;
    }

    // Separator
    doc.setDrawColor(180);
    doc.line(10, y, pageWidth - 10, y);
    y += 5;

    // Table
    const colWidths = calculateColumnWidths(headers, rows, pageWidth - 20);
    const startX = 10;
    const rowHeight = 7;
    const maxY = doc.internal.pageSize.getHeight() - 15;

    // Header row
    doc.setFillColor(41, 52, 72);
    doc.rect(startX, y - 4, pageWidth - 20, rowHeight, 'F');
    doc.setTextColor(255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    let x = startX + 2;
    headers.forEach((h, i) => {
        doc.text(String(h), x, y, { maxWidth: colWidths[i] - 4 });
        x += colWidths[i];
    });
    y += rowHeight;
    doc.setTextColor(0);
    doc.setFont('helvetica', 'normal');

    // Data rows
    rows.forEach((row, rowIndex) => {
        if (y > maxY) {
            doc.addPage();
            y = 15;
        }
        if (rowIndex % 2 === 0) {
            doc.setFillColor(245, 247, 250);
            doc.rect(startX, y - 4, pageWidth - 20, rowHeight, 'F');
        }
        x = startX + 2;
        row.forEach((cell, i) => {
            const val = typeof cell === 'number' ? cell.toLocaleString('en-IN') : String(cell);
            doc.text(val, x, y, { maxWidth: colWidths[i] - 4 });
            x += colWidths[i];
        });
        y += rowHeight;
    });

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(130);
    doc.text(`Generated by InSuite Accounts on ${new Date().toLocaleString('en-IN')}`, pageWidth / 2,
        doc.internal.pageSize.getHeight() - 5, { align: 'center' });

    doc.save(`${reportTitle.replace(/\s+/g, '_')}.pdf`);
}

// ─── Excel Export ───
export function exportToExcel(
    filename: string,
    sheetName: string,
    headers: string[],
    rows: (string | number)[][],
    company?: Company | null,
    dateRange?: { from: string; to: string }
) {
    const wsData: (string | number)[][] = [];

    // Company header rows
    if (company) {
        wsData.push([company.name || 'Company']);
        if (company.address) wsData.push([`${company.address}, ${company.city || ''} - ${company.pincode || ''}`]);
        if (company.gstin) wsData.push([`GSTIN: ${company.gstin}`]);
        wsData.push([]);
    }
    if (dateRange) {
        wsData.push([`Period: ${dateRange.from} to ${dateRange.to}`]);
        wsData.push([]);
    }

    wsData.push(headers);
    rows.forEach(r => wsData.push(r));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    // Column widths
    ws['!cols'] = headers.map((h, i) => ({
        wch: Math.max(h.length, ...rows.map(r => String(r[i] || '').length)) + 2
    }));

    XLSX.utils.book_append_sheet(wb, ws, sheetName.substring(0, 31));
    XLSX.writeFile(wb, `${filename}.xlsx`);
}

// ─── JSON Export ───
export function exportToJSON(filename: string, headers: string[], rows: (string | number)[][]) {
    const jsonData = rows.map(row => {
        const obj: Record<string, string | number> = {};
        headers.forEach((h, i) => { obj[h] = row[i]; });
        return obj;
    });
    const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
    downloadBlob(blob, `${filename}.json`);
}

// ─── Helpers ───
function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function calculateColumnWidths(headers: string[], rows: (string | number)[][], totalWidth: number): number[] {
    const maxLens = headers.map((h, i) => {
        const dataMax = rows.reduce((max, row) => Math.max(max, String(row[i] || '').length), 0);
        return Math.max(h.length, dataMax);
    });
    const totalLen = maxLens.reduce((s, l) => s + l, 0) || 1;
    return maxLens.map(l => Math.max((l / totalLen) * totalWidth, 18));
}
