import type { Company } from '../types';

/**
 * Open a styled print window with company header and report content.
 */
export function printReport(
    title: string,
    company: Company | null,
    tableHTML: string,
    dateRange?: { from: string; to: string }
) {
    const printWindow = window.open('', '_blank', 'width=900,height=700');
    if (!printWindow) { window.print(); return; }

    const companyBlock = company ? `
        <div class="company-header">
            <h1>${company.name || 'Company Name'}</h1>
            ${company.address ? `<p>${company.address}, ${company.city || ''} ${company.state || ''} - ${company.pincode || ''}</p>` : ''}
            ${company.gstin ? `<p>GSTIN: ${company.gstin}</p>` : ''}
            ${company.phone ? `<p>Phone: ${company.phone}</p>` : ''}
        </div>
    ` : '';

    const dateBlock = dateRange ? `<p class="date-range">Period: ${dateRange.from} to ${dateRange.to}</p>` : '';

    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
<title>${title}</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; padding: 20px; }
    .company-header { text-align: center; margin-bottom: 12px; padding-bottom: 10px; border-bottom: 2px solid #293448; }
    .company-header h1 { font-size: 22px; font-weight: 700; color: #293448; margin-bottom: 2px; }
    .company-header p { font-size: 11px; color: #555; margin: 1px 0; }
    .report-title { text-align: center; font-size: 17px; font-weight: 700; margin: 10px 0 4px; color: #293448; }
    .date-range { text-align: center; font-size: 11px; color: #666; margin-bottom: 14px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 11px; }
    th { background: #293448; color: #fff; padding: 7px 8px; text-align: left; font-weight: 600; font-size: 10px; text-transform: uppercase; letter-spacing: 0.3px; }
    td { padding: 6px 8px; border-bottom: 1px solid #e0e0e0; }
    tr:nth-child(even) { background: #f8f9fb; }
    tr:hover { background: #eef1f6; }
    .text-right { text-align: right; }
    .text-success { color: #0a8754; font-weight: 600; }
    .text-error { color: #d32f2f; font-weight: 600; }
    .text-bold { font-weight: 700; }
    .total-row { background: #eef1f6 !important; font-weight: 700; border-top: 2px solid #293448; }
    .summary-cards { display: flex; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; }
    .summary-card { flex: 1; min-width: 120px; padding: 10px 14px; background: #f4f6f9; border-radius: 8px; border-left: 3px solid #293448; }
    .summary-card .label { font-size: 9px; text-transform: uppercase; color: #888; letter-spacing: 0.4px; }
    .summary-card .value { font-size: 16px; font-weight: 700; color: #293448; margin-top: 2px; }
    .footer { text-align: center; font-size: 9px; color: #999; margin-top: 20px; padding-top: 8px; border-top: 1px solid #e0e0e0; }
    @media print {
        body { padding: 0; }
        .no-print { display: none !important; }
        @page { margin: 12mm; size: auto; }
    }
</style>
</head>
<body>
    ${companyBlock}
    <div class="report-title">${title}</div>
    ${dateBlock}
    ${tableHTML}
    <div class="footer">Generated by InSuite Accounts &bull; ${new Date().toLocaleString('en-IN')}</div>
    <script>
        window.onload = function() { window.print(); };
    </script>
</body>
</html>`);
    printWindow.document.close();
}

/**
 * Build HTML table from headers and rows for printing
 */
export function buildPrintTable(
    headers: string[],
    rows: (string | number)[][],
    options?: {
        totalRow?: (string | number)[];
        rightAlignCols?: number[];
    }
): string {
    const rightCols = new Set(options?.rightAlignCols || []);
    let html = '<table><thead><tr>';
    headers.forEach((h, i) => {
        html += `<th${rightCols.has(i) ? ' class="text-right"' : ''}>${h}</th>`;
    });
    html += '</tr></thead><tbody>';
    rows.forEach(row => {
        html += '<tr>';
        row.forEach((cell, i) => {
            const val = typeof cell === 'number' ? `₹${cell.toLocaleString('en-IN')}` : String(cell);
            html += `<td${rightCols.has(i) ? ' class="text-right"' : ''}>${val}</td>`;
        });
        html += '</tr>';
    });
    if (options?.totalRow) {
        html += '<tr class="total-row">';
        options.totalRow.forEach((cell, i) => {
            const val = typeof cell === 'number' ? `₹${cell.toLocaleString('en-IN')}` : String(cell);
            html += `<td${rightCols.has(i) ? ' class="text-right"' : ''}>${val}</td>`;
        });
        html += '</tr>';
    }
    html += '</tbody></table>';
    return html;
}

/**
 * Build summary cards for print
 */
export function buildPrintSummary(items: { label: string; value: string; color?: string }[]): string {
    return '<div class="summary-cards">' + items.map(item =>
        `<div class="summary-card"${item.color ? ` style="border-left-color:${item.color}"` : ''}>
            <div class="label">${item.label}</div>
            <div class="value">${item.value}</div>
        </div>`
    ).join('') + '</div>';
}
